name: Release

on:
  push:
    branches: [ main ]

jobs:
  build-dxc:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.DXC_PLATFORMS) }}
    uses: ./.github/workflows/build-dxc.yml
    name: 'build-dxc-${{ matrix.platform }}-${{ matrix.architecture }}'
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}
      
  build-spirv-cross:
    strategy:
      matrix:
        include: ${{ fromJSON(vars.SPIRV_CROSS_PLATFORMS) }}
    uses: ./.github/workflows/build-spirv-cross.yml
    name: 'build-spirv-cross-${{ matrix.platform }}-${{ matrix.architecture }}'
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  create-release:
    runs-on: ubuntu-latest
    needs: [build-dxc, build-spirv-cross]

    steps:
    - name: Get Current Date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Download Artifacts
      uses: actions/download-artifact@master
      with:
        path: ./release
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.BUILD_DATE }}
        tag_name: v${{ env.BUILD_DATE }}
        draft: true
        files: ./release/**/*.zip
