name: Release

on:
  push:
    branches: [ project-setup ]
  # workflow_dispatch:
  #   inputs:
  #     tag:
  #       description: "tag: git tag you want create. (sample 1.0.0)"
  #       required: true
  #     publish-nuget:
  #       description: "publish-nuget: true = publish nuget package. false = create the nuget puackage but don't publish it."
  #       required: true
  #       default: false
  #       type: boolean

jobs:
  build-dxc:
    strategy:
      matrix:
        platform: [macos]
        architecture: [x64, arm64]
    uses: ./.github/workflows/build-dxc.yml
    name: 'build-dxc-${{ matrix.platform }}-${{ matrix.architecture }}'
    with:
      platform: ${{ matrix.platform }}
      architecture: ${{ matrix.architecture }}

  create-release:
    runs-on: ubuntu-latest
    needs: [build-dxc]

    steps:
    - name: Get Current Date
      run: echo "BUILD_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Download Artifacts
      uses: actions/download-artifact@master
      with:
        path: ./release
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ env.BUILD_DATE }}
        tag_name: v${{ env.BUILD_DATE }}
        draft: true
        files: ./release/*
  
  #   - name: Delete Windows Native x64
  #     uses: geekyeggo/delete-artifact@v2
  #     with:
  #         name: WindowsNativex64

  #   - name: Delete MacOS Native
  #     uses: geekyeggo/delete-artifact@v2
  #     with:
  #         name: MacOSNative
          
  #   - name: Delete Dotnet Binaries
  #     uses: geekyeggo/delete-artifact@v2
  #     with:
  #         name: DotnetBinaries